Add conda activation for Ansible in Molecule job steps.  Added cleanup step to always run at the end

diff --git a/.github/workflows/ansible-role-verify.yml b/.github/workflows/ansible-role-verify.yml
--- a/.github/workflows/ansible-role-verify.yml
+++ b/.github/workflows/ansible-role-verify.yml
@@ -66,6 +66,7 @@ jobs:
       - name: Install dependencies if requirements.yml exists
         run: |
           source ~/.bashrc
+          conda activate ansible
           if [ -f requirements.yml ]; then
             ansible-galaxy install -r requirements.yml
           else
@@ -75,4 +76,12 @@ jobs:
       - name: Run Molecule tests
         run: |
           source ~/.bashrc
+          conda activate ansible
           molecule test --all
+
+      - name: Run Molecule destroy
+        if: always()
+        run: |
+          source ~/.bashrc
+          conda activate ansible
+          molecule destroy --all || true  # Ensure cleanup even if tests fail
